# Generated by Django 3.2.5 on 2021-11-28 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TwoPhaseParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('statue', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TwoPhaseValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('key', models.CharField(max_length=64)),
                ('value', models.CharField(max_length=64)),
                ('prepare_value', models.CharField(max_length=64)),
            ],
        ),
    ]
