# Generated by Django 3.2.5 on 2021-11-28 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twophase', '0002_alter_twophasevalue_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twophasevalue',
            old_name='name',
            new_name='participant',
        ),
    ]
