# Generated by Django 3.2.5 on 2021-11-28 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twophase', '0003_rename_name_twophasevalue_participant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twophaseparticipant',
            old_name='statue',
            new_name='state',
        ),
    ]
