# Generated by Django 3.2.5 on 2021-12-01 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twophase', '0005_rename_prepare_value_twophasevalue_previous_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twophasevalue',
            old_name='previous_value',
            new_name='prepared_value',
        ),
    ]
